# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'MyMovieApp' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for MyMovieApp
  #  pod 'MovieService', :path => '/Users/netomoura/Documents/Developer/MovieService'
  #  pod 'MovieService', :git => 'https://github.com/netomouraa/MovieService.git', :tag => '2.0.0'
  pod 'MovieService', :git => 'https://github.com/netomouraa/MovieService.git', :tag => '3.0.1' # Combine

  target 'MyMovieAppTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'MyMovieAppUITests' do
    # Pods for testing
  end

end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '13.0'
    end
  end
end
